#include <iostream>
using namespace std;
main(){
float a;
float b;
float c;
float d;
float e;
float f;
float g;
float h;
float i;
float j;
float k;
float l;
float m;
float n;
float o;
float A;
float p;
float s;
float r;
cout<<" enter 1st digit ";
cin>>a;
cout<<" enter 2nd digit ";
cin>>b;
cout<<" enter 3rd digit ";
cin>>c;
cout<<" enter 4th digit ";
cin>>d;
cout<<" enter 5th digit ";
cin>>e;
cout<<" enter 6th digit ";
cin>>f;
cout<<" enter 7th digit ";
cin>>g;
cout<<" enter 8th digit ";
cin>>h;
cout<<" enter 9th digit ";
cin>>i;
cout<<" enter 10th digit ";
cin>>j;
cout<<" enter 11th digit ";
cin>>k;
cout<<" enter 12th digit ";
cin>>l;
cout<<" enter 13th digit ";
cin>>m;
cout<<" enter 14th digit ";
cin>>n;
cout<<" enter 15th digit ";
cin>>o;
A=a+b+c+d+e;
p=f*g*h*i*j;
s=k-l-m-n-o;
r=A+p-s;
cout<<"the result is "<<r;
}